# Generated by Django 4.2.7 on 2024-01-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='local_area',
            field=models.CharField(blank=True, default='', max_length=220, null=True, verbose_name='Area/Locale'),
        ),
    ]
