# Generated by Django 4.2.9 on 2024-01-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Pickup', 'Pickup'), ('Suv', 'Suv'), ('Convertible', 'Convertible'), ('Crossover', 'Crossover'), ('Mpv', 'Mpv'), ('Sedan', 'Sedan'), ('Truck', 'Truck'), ('Electric', 'Electric'), ('Luxury', 'Luxury'), ('Wagon', 'Wagon'), ('Compact', 'Compact'), ('Sports', 'Sports')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carswap',
            name='body_type',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Pickup', 'Pickup'), ('Suv', 'Suv'), ('Convertible', 'Convertible'), ('Crossover', 'Crossover'), ('Mpv', 'Mpv'), ('Sedan', 'Sedan'), ('Truck', 'Truck'), ('Electric', 'Electric'), ('Luxury', 'Luxury'), ('Wagon', 'Wagon'), ('Compact', 'Compact'), ('Sports', 'Sports')], max_length=100),
        ),
    ]
